# Welcome to Jekyll!

# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Circular
email: simonleijon59@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Circular is a personal website and blog. The blog covers software development, data science, and 
  really anything and everything that interests the author. Posts are not meant to be comprehensive or 
  complete but rather a short exploration of a topic. The website is built using Jekyll and hosted on
  GitHub Pages. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/sleijon1" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/simon-leijon-402897133/" }
show_excerpts: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
